theme = "catppuccin_mocha"

[editor]
cursorline = true
# line-number = "absolute"
line-number = "relative"
middle-click-paste = false
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
